server:
  port: 19008

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.thinkit.microservicecloud.entities.console   # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: microservicecloud-console
   redis:
        database: 0
        host: 192.168.11.173
        port: 6379
        pool:
           max-active: 8
           max-idle: 8
           min-idle: 0
           max-wait: -1
        timeout: 5000
      # password: test


   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://192.168.14.215:3306/thinkit?useUnicode=true&characterEncoding=utf8             # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间




eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
       defaultZone: http://localhost:18082/eureka
       #defaultZone: http://www.eureka02.com:18082/eureka/,http://www.eureka01.com:18081/eureka/
  instance:
    instance-id: microservicecloud-provider-console-p19008
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: thinkit-microservicecloud
  company.name: www.thinkit.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


#验证码服务
verification:
   ServerIp: 47.93.234.184
   ServerPort:  80

logging:
  config: classpath:logback-thinkit.xml

personal_certificate:
      filepath: D:/Voice/personal/picture/

company_certificate:
      filepath: D:/Voice/company/picture/

sdk:
  offline_asr_doc: D:/Voice/sdk/基于语音流方式离线语音转写系统接口开发规范V1.0.2.pdf

