server:
  port: 20007
eureka:
  client:
    register-with-eureka: false
    service-url:
       #defaultZone:  http://www.eureka02.com:18082/eureka/,http://www.eureka01.com:18081/eureka/
       defaultZone:  http://127.0.0.1:18082/eureka/,http://127.0.0.1:18081/eureka/

logging:
  config: classpath:logback-thinkit.xml